//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Bussiness.WmsToPTLServer {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IForWmsService", Namespace="http://tempuri.org/")]
    public partial class ForWmsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StartOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinishOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ForWmsService() {
            this.Url = global::Bussiness.Properties.Settings.Default.Bussiness_WmsToPTLServer_ForWmsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StartCompletedEventHandler StartCompleted;
        
        /// <remarks/>
        public event FinishCompletedEventHandler FinishCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ARIS/PickToLight/IForWmsService/Start", RequestNamespace="http://ARIS/PickToLight", ResponseNamespace="http://ARIS/PickToLight", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Start([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string areaCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string orderCode) {
            this.Invoke("Start", new object[] {
                        areaCode,
                        orderCode});
        }
        
        /// <remarks/>
        public void StartAsync(string areaCode, string orderCode) {
            this.StartAsync(areaCode, orderCode, null);
        }
        
        /// <remarks/>
        public void StartAsync(string areaCode, string orderCode, object userState) {
            if ((this.StartOperationCompleted == null)) {
                this.StartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartOperationCompleted);
            }
            this.InvokeAsync("Start", new object[] {
                        areaCode,
                        orderCode}, this.StartOperationCompleted, userState);
        }
        
        private void OnStartOperationCompleted(object arg) {
            if ((this.StartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ARIS/PickToLight/IForWmsService/Finish", RequestNamespace="http://ARIS/PickToLight", ResponseNamespace="http://ARIS/PickToLight", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Finish([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string areaCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string orderCode) {
            this.Invoke("Finish", new object[] {
                        areaCode,
                        orderCode});
        }
        
        /// <remarks/>
        public void FinishAsync(string areaCode, string orderCode) {
            this.FinishAsync(areaCode, orderCode, null);
        }
        
        /// <remarks/>
        public void FinishAsync(string areaCode, string orderCode, object userState) {
            if ((this.FinishOperationCompleted == null)) {
                this.FinishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinishOperationCompleted);
            }
            this.InvokeAsync("Finish", new object[] {
                        areaCode,
                        orderCode}, this.FinishOperationCompleted, userState);
        }
        
        private void OnFinishOperationCompleted(object arg) {
            if ((this.FinishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinishCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void StartCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void FinishCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591